name: Selenium UI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

      nginx:
        image: nginx:alpine
        ports:
          - 80:80
        volumes:
          - ./html:/usr/share/nginx/html:ro

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install selenium-webdriver

      - name: Wait for Selenium to be ready
        run: |
          for i in {1..10}; do
            echo "Checking if Selenium is ready (attempt $i)..."
            curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true' && break
            sleep 3
          done

      - name: Run Selenium Test
        run: node tests/SeleniumTest.mjs
