name: Selenium UI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

      nginx:
        image: nginx:alpine
        ports:
          - 80:80
        volumes:
          - ./html:/usr/share/nginx/html

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Selenium WebDriver
        run: npm install selenium-webdriver

      - name: Run Selenium Test
        run: node tests/SeleniumTest.mjs

