name: Selenium UI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install selenium-webdriver

      - name: Install static server
        run: npm install -g http-server

      - name: Serve static HTML
        run: |
          nohup http-server ./html -p 8080 > server.log 2>&1 &
          sleep 5  # Give it time to start
          curl -f http://localhost:8080 || { echo "Static server failed to start"; cat server.log; exit 1; }

      - name: Wait for Selenium to be ready
        run: |
          for i in {1..10}; do
            echo "Checking if Selenium is ready (attempt $i)..."
            curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true' && break
            sleep 3
          done

      - name: Run Selenium Test
        run: node tests/SeleniumTest.mjs
