name: Selenium UI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --health-cmd="curl -s http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      nginx:
        image: nginx:alpine
        ports:
          - 80:80
        volumes:
          - ./html:/usr/share/nginx/html

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Selenium WebDriver
        run: npm install selenium-webdriver

      - name: Wait for services
        run: |
          sleep 10
          curl -f http://localhost || exit 1
          curl -f http://localhost:4444/wd/hub/status || exit 1

      - name: Run Selenium Test
        run: node tests/SeleniumTest.mjs
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub

